config/routes.rb
ActivityRoutePlanner::Application.routes.draw do
  

  resources :tests

  root :to => "init#index"
  match "answer" => "tests#answer"
  match "test" => "tests#begintest"
  match "end" => "tests#endtest"
  match "get_algo_dynamic_content" => "init#get_algo_dynamic_content"
  match "calculate_route" => "calculate_route#calculate_route"
  match "update_point" => "point#update_point"
  match "remove_point" => "point#remove_point"
  match "add_activity" => "activity#create"
  match "move" => "activity#move"
  match "delete_activity" => "activity#update_activity"
  match "reset" => "init#index"
  match "reset_method" => "init#reset"
  match "check_edge" => "calculate_route#calculate_route"
  match "set_route_parameters"=>"calculate_route#set_route_parameters"
  match "load_content"=>"content_loader#load_content"
  match "search"=>"geocoder#search", :as => :geocoder_search
  match "ontosearch"=>"ontology_search#ontosearch"
  match "get_energy"=>"calculate_route#get_energy_route"
  match "activity/list" => "activity#list"
  match "activity/search" => "activity#search", :as => :activity_search
  match "freetext" => "init#freetext"
  match "fa37_jnc_c_hry_dsbzayy4c_bw_dx_s22_jjz/index" => "display#index"
  match "fa37_jnc_c_hry_dsbzayy4c_bw_dx_s22_jjz/black" => "display#black"
  

end

app/models/ontology.rb
class Ontology < ActiveRecord::Base
  # ontologies
  # database fields  
  # name: name of the ontology
  # url: its url (perhaps needed for Protégé)
  
  require 'rexml/document'
  include REXML
  has_many :ontology_classes, :dependent => :destroy
  
  # get all root classes
  def roots
    self.ontology_classes(force_reload=true).select{|c| c.isroot?}
  end

  # read in an OWL ontology in the XML format
  def self.read_ontology(filename,ontologyname)
    xmlfile = File.open(filename)
    xmldoc = Document.new(xmlfile)
    classes = {}
    o = Ontology.create({:name => ontologyname})
    xmldoc.elements.each("rdf:RDF/owl:Class") do |e|
      name = element_about(e)
      c = OntologyClass.new
      c.name = name
      c.ontology = o
      c.save
      classes[name] = c
    end   
    xmldoc.elements.each("rdf:RDF/owl:Class/rdfs:subClassOf") do |e|
      onto_child = classes[element_about(e.parent)] # the XML parent is the ontological child
      onto_parent = classes[element_attr(e,"resource")]
      onto_parent.subclasses << onto_child
    end
    roots = o.roots
    name = "Thing"
    thing = OntologyClass.new
    thing.name = name
    thing.ontology = o
    thing.save
    thing.subclasses = roots
    return o
  end
  
  # get attribute of an xml element
  def self.element_attr(e,attr)
    return e.attributes[attr][1,10000] 
  end
  # get name of an xml element
  def self.element_about(e)
    return element_attr(e,"about") 
  end  
end

app/controllers/ontologies_controller.rb
class OntologiesController < ApplicationController
  # GET /ontologies
  # GET /ontologies.xml
  def index
    @ontologies = Ontology.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ontologies }
    end
  end

  # GET /ontologies/1
  # GET /ontologies/1.xml
  def show
    @ontology = Ontology.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ontology }
    end
  end

  # GET /ontologies/new
  # GET /ontologies/new.xml
  def new
    @ontology = Ontology.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ontology }
    end
  end

  # GET /ontologies/1/edit
  def edit
    @ontology = Ontology.find(params[:id])
  end

  # POST /ontologies
  # POST /ontologies.xml
  def create
    @ontology = Ontology.new(params[:ontology])

    respond_to do |format|
      if @ontology.save
        format.html { redirect_to(@ontology, :notice => 'Ontology was successfully created.') }
        format.xml  { render :xml => @ontology, :status => :created, :location => @ontology }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ontology.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ontologies/1
  # PUT /ontologies/1.xml
  def update
    @ontology = Ontology.find(params[:id])

    respond_to do |format|
      if @ontology.update_attributes(params[:ontology])
        format.html { redirect_to(@ontology, :notice => 'Ontology was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ontology.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ontologies/1
  # DELETE /ontologies/1.xml
  def destroy
    @ontology = Ontology.find(params[:id])
    @ontology.destroy

    respond_to do |format|
      format.html { redirect_to(ontologies_url) }
      format.xml  { head :ok }
    end
  end

  def tree
    @ontology = Ontology.find(params[:id])
    @root = @ontology.roots[0]
  end
  
  def search
    @ontology = Ontology.find_by_name("activities")
    @classes = OntologyClass.find(:all,:conditions=>
         ["name like ? and ontology_id = ?","%#{params[:search]}%",@ontology.id])    
  end

  def maketxt
    Ontology.write_js_text_files  
  end

end

app/views/ontologies/_tree.html.erb
<%= tree.name%>
<ul>
<% for c in tree.subclasses %>
  <% if !c.nil? %>
  <li>
   <%= render :partial => 'tree', :object => c %>
  </li>  
  <% end %>
<% end %>
</ul>

app/views/ontologies/edit.html.erb
<h1>Editing ontology</h1>

<% form_for(@ontology) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @ontology %> |
<%= link_to 'Back', ontologies_path %>

app/views/ontologies/index.html.erb
<h1>Listing ontologies</h1>

<%= form_tag ("/ontologies/search") %>
Search: <%= text_field_tag :search, "", :size => 20 %>
</form>
<%= link_to 'Make txt', "/ontologies/maketxt" %>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
  </tr>

<% @ontologies.each do |ontology| %>
  <tr>
    <td><%=h ontology.name %></td>
    <td><%=h ontology.url %></td>
    <td><%= link_to 'Show', "/ontologies/#{ontology.id}/tree" %></td>
    <td><%= link_to 'Edit', edit_ontology_path(ontology) %></td>
    <td><%= link_to 'Destroy', ontology, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New ontology', new_ontology_path %>

app/views/ontologies/new.html.erb
<h1>New ontology</h1>

<% form_for(@ontology) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', ontologies_path %>

app/views/ontologies/search.html.erb
<h1> Results of search</h1>

<table>
<% for c in @classes %>
  <tr><td><%= c.name%></td></tr>
<% end %>
</table>

app/views/ontologies/show.html.erb
<p>
  <b>Name:</b>
  <%=h @ontology.name %>
</p>

<p>
  <b>Url:</b>
  <%=h @ontology.url %>
</p>


<%= link_to 'Edit', edit_ontology_path(@ontology) %> |
<%= link_to 'Back', ontologies_path %>

app/views/ontologies/tree.html.erb
<h1> Ontology <%= @ontology.name %></h1>

 <%= render :partial => 'tree', :object => @root %>